language: python

python:
  - '3.5'

addons:
    postgresql: "9.5"

services:
    - redis-server

env:
  global:
    - DJANGO_SECRET_KEY='secret key just for testing'
    - DJANGO_CONFIGURATION='Travis'

install:
  - pip install -r requirements-dev.txt

before_script:
  - psql -U postgres -c "create extension postgis"
  - psql -U postgres -c "create user test_app with superuser password 'testpassword';"
  - psql -U postgres -c "create database test_db;"

script:
  - py.test --pep8 --cov community
